listener:
  tcp:
    address: 0.0.0.0
    port: 8080
    secure: false

logger:
  pretty: true
  level: DEBUG

database:
  host: ${DB_HOST}
  port: ${DB_PORT}
  name: ${DB_NAME}
  username: ${DB_USERNAME}
  password: ${DB_PASSWORD}

tenants:
  - tenant_id: ${TENANT_ID1}
    tenant_api_key: ${TENANT_API_KEY1}
    list_game_url: ${LIST_GAME_URL1}
  - tenant_id: ${TENANT_ID2}
    tenant_api_key: ${TENANT_API_KEY2}
    list_game_url: ${LIST_GAME_URL2}

auth:
  player_signing:
    signing_key: ${PLAYER_SIGNING_KEY}
    audience: player
    issuer: demo

  tenant_player_signing:
    signing_key: ${TENANT_PLAYER_SIGNING_KEY}
    audience: tenant_player
    issuer: demo