listener:
  tcp:
    address: 0.0.0.0
    port: 8080
    secure: false

logger:
  pretty: true
  level: DEBUG

database:
  host: ${DB_HOST}
  port: ${DB_PORT}
  name: ${DB_NAME}
  username: ${DB_USERNAME}
  password: ${DB_PASSWORD}

