// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/nautilusgames/demo/auth/internal/ent/player"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/entql"
	"entgo.io/ent/schema/field"
)

// schemaGraph holds a representation of ent/schema at runtime.
var schemaGraph = func() *sqlgraph.Schema {
	graph := &sqlgraph.Schema{Nodes: make([]*sqlgraph.Node, 1)}
	graph.Nodes[0] = &sqlgraph.Node{
		NodeSpec: sqlgraph.NodeSpec{
			Table:   player.Table,
			Columns: player.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt64,
				Column: player.FieldID,
			},
		},
		Type: "Player",
		Fields: map[string]*sqlgraph.FieldSpec{
			player.FieldUsername:       {Type: field.TypeString, Column: player.FieldUsername},
			player.FieldHashedPassword: {Type: field.TypeString, Column: player.FieldHashedPassword},
			player.FieldDisplayName:    {Type: field.TypeString, Column: player.FieldDisplayName},
			player.FieldCreatedAt:      {Type: field.TypeTime, Column: player.FieldCreatedAt},
		},
	}
	return graph
}()

// predicateAdder wraps the addPredicate method.
// All update, update-one and query builders implement this interface.
type predicateAdder interface {
	addPredicate(func(s *sql.Selector))
}

// addPredicate implements the predicateAdder interface.
func (pq *PlayerQuery) addPredicate(pred func(s *sql.Selector)) {
	pq.predicates = append(pq.predicates, pred)
}

// Filter returns a Filter implementation to apply filters on the PlayerQuery builder.
func (pq *PlayerQuery) Filter() *PlayerFilter {
	return &PlayerFilter{config: pq.config, predicateAdder: pq}
}

// addPredicate implements the predicateAdder interface.
func (m *PlayerMutation) addPredicate(pred func(s *sql.Selector)) {
	m.predicates = append(m.predicates, pred)
}

// Filter returns an entql.Where implementation to apply filters on the PlayerMutation builder.
func (m *PlayerMutation) Filter() *PlayerFilter {
	return &PlayerFilter{config: m.config, predicateAdder: m}
}

// PlayerFilter provides a generic filtering capability at runtime for PlayerQuery.
type PlayerFilter struct {
	predicateAdder
	config
}

// Where applies the entql predicate on the query filter.
func (f *PlayerFilter) Where(p entql.P) {
	f.addPredicate(func(s *sql.Selector) {
		if err := schemaGraph.EvalP(schemaGraph.Nodes[0].Type, p, s); err != nil {
			s.AddError(err)
		}
	})
}

// WhereID applies the entql int64 predicate on the id field.
func (f *PlayerFilter) WhereID(p entql.Int64P) {
	f.Where(p.Field(player.FieldID))
}

// WhereUsername applies the entql string predicate on the username field.
func (f *PlayerFilter) WhereUsername(p entql.StringP) {
	f.Where(p.Field(player.FieldUsername))
}

// WhereHashedPassword applies the entql string predicate on the hashed_password field.
func (f *PlayerFilter) WhereHashedPassword(p entql.StringP) {
	f.Where(p.Field(player.FieldHashedPassword))
}

// WhereDisplayName applies the entql string predicate on the display_name field.
func (f *PlayerFilter) WhereDisplayName(p entql.StringP) {
	f.Where(p.Field(player.FieldDisplayName))
}

// WhereCreatedAt applies the entql time.Time predicate on the created_at field.
func (f *PlayerFilter) WhereCreatedAt(p entql.TimeP) {
	f.Where(p.Field(player.FieldCreatedAt))
}
