listener:
  tcp:
    address: 0.0.0.0
    port: 8080
    secure: false

logger:
  pretty: true
  level: DEBUG

database:
  host: ${DB_HOST}
  port: ${DB_PORT}
  name: ${DB_NAME}
  username: ${DB_USERNAME}
  password: ${DB_PASSWORD}

tenant_id: ${TENANT_ID}
tenant_api_key: ${TENANT_API_KEY}
tenant_token_url: ${TENANT_TOKEN_URL}

auth:
  player_signing:
    signing_key: ${PLAYER_SIGNING_KEY}
    audience: access_token
    issuer: demo

  player_tenant_signing:
    signing_key: ${PLAYER_TENANT_SIGNING_KEY}
    audience: player_tenant_token
    issuer: demo

